### PR TITLE
Better diff

### PR DESCRIPTION
**Pull request by giacomocavalieri**

### CODE REVIEW

**Comment by JohnBjrk** [comment]
@giacomocavalieri I saw that you replaced gap with another algorithm in this PR. Just got a bit curious about the reason just to understand if there is a use-case which gap currently doesn't support? (I'm the author of gap)

**Comment by giacomocavalieri** [comment]
Hello!! Yes I switched to a custom implementation because I wanted to use the histogram diffing algorithm and I didn't know how to get gap to use that when comparing two strings

**Comment by JohnBjrk** [comment]
Thanks for the response 🙏 
I'll have to look into the possibility of adding this algorithm at some point. My first implementation used a standard dynamic programming LCS algorithm, but then I switched to Myers as default in order to improve performance.

**Comment by JohnBjrk** [comment]
I had a quick look at your implementation just to see if I could understand
how the algorithm works and I saw that you had made some comments about
performance optimizations. Also I didn’t quite grasp how everything worked,
but that’s probably more on me to not have read up on the algorithm
properly.

Anyway if you want to adapt in and make a PR to gap you are of course more
than welcome to. Otherwise I might see if I can figure something out at
some point when I have some time.

tis 13 feb. 2024 kl. 20:51 skrev Giacomo Cavalieri ***@***.***

**Comment by giacomocavalieri** [comment]
If you want to learn more you can have a read here, it's a great resource https://tiarkrompf.github.io/notes/?/diff-algorithm/

My implementation is a translation of that algorithm with some tweaks for a pure functional setting

**Pull request merged**
